# Generated by Django 4.0.4 on 2022-05-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='uni_management.courses'),
        ),
        migrations.AddField(
            model_name='students',
            name='session_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uni_management.sessionyearmodel'),
        ),
    ]
